name: Publish Release

on:
  release:
    types:
      - created
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: get_tag
        name: Get Tag
        env:
          GITHUB_HEAD_REF: $${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
        run: |
          if [ "${{ github.event.inputs.version }}" = "" ]
          then
            TAG=$(jq --raw-output '.release.tag_name' $GITHUB_EVENT_PATH)
          else
            TAG=${{ github.event.inputs.version }}
          fi
          
          echo $TAG > semantic.version
          
          echo ::set-output name=TAG::$TAG
      - name: Build Godot Project
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: TetraForce
          preset: linux
          projectDir: '.'
          debugMode: 'true'
      - name: Get Docker Repo Name
        id: find_repo
        run: |
          REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=REPO::$REPO
      - name: Push Tag to GitHub Package
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: "docker.pkg.github.com/${{ steps.find_repo.outputs.REPO }}"
          BUILD_PATH: "."
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "tetraforce"
          TAG_NAME: ${{ steps.get_tag.outputs.TAG }}
          LATEST: "true"
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: TetraForce.x86_64
          preset: linux
          projectDir: '.'
          debugMode: 'true'
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - linux
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Package
        run: |
          cd ${{ steps.build.outputs.build }}
          mkdir -p ${{github.workspace}}/tetraforce
          zip -r ${{github.workspace}}/tetraforce/TetraForce.zip .
      - name: Ship to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: tetraforce-public-production-us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          SOURCE_DIR: ${{github.workspace}}/tetraforce
          DEST_DIR: builds/master/latest/linux
  windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win32, win64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: TetraForce.exe
          preset: ${{ matrix.platform }}
          projectDir: '.'
          debugMode: 'true'
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Package
        run: |
          cd ${{ steps.build.outputs.build }}
          mkdir -p ${{github.workspace}}/tetraforce
          zip -r ${{github.workspace}}/tetraforce/TetraForce.zip .
      - name: Ship to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: tetraforce-public-production-us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          SOURCE_DIR: ${{github.workspace}}/tetraforce
          DEST_DIR: builds/master/latest/${{ matrix.platform }}
  osx:
    name: Build OSX
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Godot
        run: |
          brew install --cask godot
          ln -s /Applications/Godot.app/Contents/MacOS/Godot /usr/local/bin/godot
      - name: Build Project
        run: |
          wget https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_export_templates.tpz -q
          unzip Godot_v3.2.3-stable_export_templates.tpz -d .
          mkdir -p "/Users/runner/Library/Application Support/Godot/templates/3.2.3.stable"
          mv templates/* "/Users/runner/Library/Application Support/Godot/templates/3.2.3.stable"

          mkdir -p $GITHUB_WORKSPACE/build
          godot --export osx $GITHUB_WORKSPACE/build/TetraForce.dmg
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: "Client - OSX"
          path: ${{ github.workspace }}/build/TetraForce.dmg
  publish_osx:
    name: Publish OSX
    runs-on: ubuntu-latest
    needs: osx
    steps:
    - name: Download Build
      uses: actions/download-artifact@v2
      with:
        name: "Client - OSX"
    - name: Configure
      run: |
        mkdir tetraforce
        mv "Client - OSX" ./tetraforce/TetraForce.zip
    - name: Ship to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: tetraforce-public-production-us-east-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-2
        SOURCE_DIR: ${{github.workspace}}/tetraforce
        DEST_DIR: builds/master/latest/osx