name: Build Godot Project
on:
  push:
    branches:
      - master

jobs:
  godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, osx, win32, win64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          if [ "$PLATFORM" = "win32" ] || [ "$PLATFORM" = "win64" ] ; then
            echo "::set-env name=EXPORT_SUFFIX::.exe"
          fi
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: TetraForce${{ env.EXPORT_SUFFIX }}
          preset: ${{ matrix.platform }}
          projectDir: '.'
          debugMode: 'true'
          package: 'true'
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Ship to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          SOURCE_DIR: ${{ steps.build.outputs.artifact }}
          AWS_REGION: "us-east-2"
          DEST_DIR: builds/master/latest
          AWS_S3_BUCKET: tetraforce-releases-production-us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}